// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_AutoRenta.Context;

namespace Proyecto_AutoRenta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230720222617_example")]
    partial class example
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Reserve", b =>
                {
                    b.Property<int>("PkReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FkVehiculos")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkReserva");

                    b.HasIndex("FkVehiculos");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            PkReserva = 1,
                            Correo = "correo1@example.com",
                            FkVehiculos = 1,
                            Nombre = "Usuario1",
                            Telefono = "123456789"
                        },
                        new
                        {
                            PkReserva = 2,
                            Correo = "correo2@example.com",
                            FkVehiculos = 3,
                            Nombre = "Usuario2",
                            Telefono = "987654321"
                        },
                        new
                        {
                            PkReserva = 3,
                            Correo = "correo3@example.com",
                            FkVehiculos = 2,
                            Nombre = "Usuario3",
                            Telefono = "555555555"
                        },
                        new
                        {
                            PkReserva = 4,
                            Correo = "correo4@example.com",
                            FkVehiculos = 5,
                            Nombre = "Usuario4",
                            Telefono = "999999999"
                        },
                        new
                        {
                            PkReserva = 5,
                            Correo = "correo5@example.com",
                            FkVehiculos = 4,
                            Nombre = "Usuario5",
                            Telefono = "444444444"
                        });
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Rol", b =>
                {
                    b.Property<int>("PkRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            PkRol = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            PkRol = 2,
                            Nombre = "Usuario"
                        },
                        new
                        {
                            PkRol = 3,
                            Nombre = "Editor"
                        },
                        new
                        {
                            PkRol = 4,
                            Nombre = "Invitado"
                        },
                        new
                        {
                            PkRol = 5,
                            Nombre = "Supervisor"
                        });
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Usuario", b =>
                {
                    b.Property<int>("PkUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkUsuario");

                    b.HasIndex("FkRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Vehiculos", b =>
                {
                    b.Property<int>("PkVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Tarifa")
                        .HasColumnType("double");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkVehiculo");

                    b.ToTable("Vehiculo");

                    b.HasData(
                        new
                        {
                            PkVehiculo = 1,
                            Modelo = "Modelo1",
                            Tarifa = 1000.0,
                            Tipo = "Tipo1"
                        },
                        new
                        {
                            PkVehiculo = 2,
                            Modelo = "Modelo2",
                            Tarifa = 1500.0,
                            Tipo = "Tipo2"
                        },
                        new
                        {
                            PkVehiculo = 3,
                            Modelo = "Modelo3",
                            Tarifa = 1200.0,
                            Tipo = "Tipo1"
                        },
                        new
                        {
                            PkVehiculo = 4,
                            Modelo = "Modelo4",
                            Tarifa = 2000.0,
                            Tipo = "Tipo3"
                        },
                        new
                        {
                            PkVehiculo = 5,
                            Modelo = "Modelo5",
                            Tarifa = 1800.0,
                            Tipo = "Tipo2"
                        });
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Reserve", b =>
                {
                    b.HasOne("Proyecto_AutoRenta.Entities.Vehiculos", "Vehiculos")
                        .WithMany()
                        .HasForeignKey("FkVehiculos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Usuario", b =>
                {
                    b.HasOne("Proyecto_AutoRenta.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FkRol");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
