// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_AutoRenta.Context;

namespace Proyecto_AutoRenta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230730223445_Example")]
    partial class Example
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Reserve", b =>
                {
                    b.Property<int>("PkReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegreso")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime");

                    b.Property<int>("FkUsuario")
                        .HasColumnType("int");

                    b.Property<int>("FkVehiculos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.HasKey("PkReserva");

                    b.HasIndex("FkUsuario");

                    b.HasIndex("FkVehiculos");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Rol", b =>
                {
                    b.Property<int>("PkRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            PkRol = 1,
                            Nombre = "SuperAdmin"
                        },
                        new
                        {
                            PkRol = 2,
                            Nombre = "GestorReserva"
                        },
                        new
                        {
                            PkRol = 3,
                            Nombre = "GestorInventario"
                        });
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Usuario", b =>
                {
                    b.Property<int>("PkUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkUsuario");

                    b.HasIndex("FkRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            PkUsuario = 1,
                            FkRol = 1,
                            Nombre = "Jony",
                            Password = "admin",
                            UserName = "admin"
                        },
                        new
                        {
                            PkUsuario = 2,
                            FkRol = 2,
                            Nombre = "Jero",
                            Password = "123",
                            UserName = "123"
                        },
                        new
                        {
                            PkUsuario = 3,
                            FkRol = 3,
                            Nombre = "Jhordi",
                            Password = "1234",
                            UserName = "1234"
                        });
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Vehiculos", b =>
                {
                    b.Property<int>("PkVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Tarifa")
                        .HasColumnType("double");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkVehiculo");

                    b.ToTable("Vehiculo");

                    b.HasData(
                        new
                        {
                            PkVehiculo = 1,
                            Modelo = "Nissan",
                            Tarifa = 123.0,
                            Tipo = "Deportivo"
                        },
                        new
                        {
                            PkVehiculo = 2,
                            Modelo = "Chevrolet",
                            Tarifa = 300.0,
                            Tipo = "Super"
                        });
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Reserve", b =>
                {
                    b.HasOne("Proyecto_AutoRenta.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("FkUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_AutoRenta.Entities.Vehiculos", "Vehiculos")
                        .WithMany()
                        .HasForeignKey("FkVehiculos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Proyecto_AutoRenta.Entities.Usuario", b =>
                {
                    b.HasOne("Proyecto_AutoRenta.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FkRol");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
